# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

kind-dependencies:
    - build
    - fetch

transforms:
    - taskgraph.transforms.build_attrs:transforms
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    attributes:
        nightly: true
    description: "Extract geckodriver binary from common tests package"
    treeherder:
        kind: other
        symbol: Gd(repack)
        tier: 2
    worker-type: b-linux
    worker:
        max-run-time: 1200
        docker-image: {in-tree: debian9-amd64-build}
        chain-of-trust: true
    run:
        using: run-task
        checkout: false

jobs:
    linux-nightly/opt:
        treeherder:
            platform: linux32/opt
        dependencies:
            build-linux/opt: build-linux-shippable/opt
        fetches:
            build-linux/opt:
                - artifact: target.common.tests.tar.gz
        worker:
            artifacts:
                - type: file
                  name: public/geckodriver.tar.gz
                  path: /builds/worker/geckodriver.tar.gz
        run-on-projects: ['try', 'release']  # Do not run on autoland, Bug 1599197
        run:
            command: >
                cd /builds/worker/fetches/bin/ &&
                tar -cvzf geckodriver.tar.gz geckodriver &&
                cp geckodriver.tar.gz /builds/worker

    linux64-nightly/opt:
        treeherder:
            platform: linux64/opt
        dependencies:
            build-linux64/opt: build-linux64-shippable/opt
        fetches:
            build-linux64/opt:
                - artifact: target.common.tests.tar.gz
        worker:
            artifacts:
                - type: file
                  name: public/geckodriver.tar.gz
                  path: /builds/worker/geckodriver.tar.gz
        run:
            command: >
                cd /builds/worker/fetches/bin/ &&
                tar -cvzf geckodriver.tar.gz geckodriver &&
                cp geckodriver.tar.gz /builds/worker

    macosx64-nightly/opt:
        treeherder:
            platform: osx-cross/opt
        dependencies:
            build-macosx64/opt: build-macosx64-shippable/opt
        fetches:
            build-macosx64/opt:
                - artifact: target.common.tests.tar.gz
        worker:
            artifacts:
                - type: file
                  name: public/geckodriver.tar.gz
                  path: /builds/worker/geckodriver.tar.gz
        run:
            command: >
                cd /builds/worker/fetches/bin/ &&
                tar -cvzf geckodriver.tar.gz geckodriver &&
                cp geckodriver.tar.gz /builds/worker

    win32-nightly/opt:
        treeherder:
            platform: windows2012-32/opt
        dependencies:
            build-win32/opt: build-win32-shippable/opt
        fetches:
            build-win32/opt:
                - artifact: target.common.tests.tar.gz
        worker:
            artifacts:
                - type: file
                  name: public/geckodriver.zip
                  path: /builds/worker/geckodriver.zip
        run:
            command: >
                cd /builds/worker/fetches/bin/ &&
                zip -r geckodriver.zip geckodriver.exe &&
                cp geckodriver.zip /builds/worker

    win64-nightly/opt:
        treeherder:
            platform: windows2012-64/opt
        dependencies:
            build-win64/opt: build-win64-shippable/opt
        fetches:
            build-win64/opt:
                - artifact: target.common.tests.tar.gz
        worker:
            artifacts:
                - type: file
                  name: public/geckodriver.zip
                  path: /builds/worker/geckodriver.zip
        run:
            command: >
                cd /builds/worker/fetches/bin/ &&
                zip -r geckodriver.zip geckodriver.exe &&
                cp geckodriver.zip /builds/worker
