API_ROOT = 'http://balrogadmin.ghosterydev.com/api'
PRODUCT_NAME = 'Ghostery'
AUTH0_AUDIENCE = 'ghostery-balrog'
AUTH0_DOMAIN = 'ghostery-balrog.eu.auth0.com'
REPOSITORY_BASE_URL = 'https://github.com/ghostery/user-agent-desktop/releases/download'