# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.push_apk:loader

transforms:
    - taskgraph.transforms.push_apk_checks:transforms
    - taskgraph.transforms.task:transforms

kind-dependencies:
    - build-signing

jobs:
    push-apk-checks/opt:
        description: Verify APKs are sane before uploading them onto Google Play Store
        attributes:
            build_platform: android-nightly
            nightly: true
        shipping-phase: promote
        shipping-product: fennec
        package-name:
            by-project:
                mozilla-central: org.mozilla.fennec_aurora
                mozilla-beta: org.mozilla.firefox_beta
                mozilla-release: org.mozilla.firefox
                default: org.mozilla.fennec_aurora
        worker-type: b-linux
        worker:
            implementation: docker-worker
            os: linux
            docker-image: {in-tree: mozapkpublisher}
            chain-of-trust: true
            max-run-time: 600
        treeherder:
            symbol: pub(gpc)
            platform: Android/opt
            tier: 1
            kind: test
        run-on-projects: ['mozilla-central', 'mozilla-beta', 'mozilla-release']
